testsite/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView,logout

app_name='accounts'

urlpatterns=[
    url(r'^$',views.home,name='home'),
    url(r'^about/$',views.about,name='about'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',logout,{'template_name':'accounts/logout.html'},name='logout'),
    url(r'^register/$',views.register,name='register'),
    url(r'^entertainment/(?P<slug>[\w-]+)/$',views.person_detail,name='detail'),
    url(r'^motivational/(?P<slug>[\w-]+)/$',views.moti_detail,name='moti'),
    url(r'^tech/(?P<slug>[\w-]+)/$',views.tech_detail,name='tech'),
    url(r'^music/(?P<slug>[\w-]+)/$',views.music_detail,name='music'),
]

testsite/testsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf  import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.login_redirect,name='login_redirect'),
    url(r'^account/',include('accounts.urls')),
    url(r'^allchannel/',include('allchannel.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

testsite/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100,default='')
    about = models.TextField(max_length=100000,default='')
    link = models.CharField(max_length=500,default='')
    image = models.ImageField(blank=True)
    suscriber = models.CharField(max_length=10,default=None)

    def __str__(self):
        return self.name

    def snippet(self):
        return self.about[0:60]

class motivational(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100,default='')
    about = models.TextField(max_length=100000,default='')
    link = models.CharField(max_length=500,default='')
    image = models.ImageField(blank=True)
    suscriber = models.CharField(max_length=10,default=None)
    def __str__(self):
        return self.name

    def snippet(self):
        return self.about[0:60]


class tech(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100,default='')
    about = models.TextField(max_length=100000,default='')
    link = models.CharField(max_length=500,default='')
    image = models.ImageField(blank=True)
    suscriber = models.CharField(max_length=10,default=None)
    def __str__(self):
        return self.name

    def snippet(self):
        return self.about[0:60]


class music(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100,default='')
    about = models.TextField(max_length=100000,default='')
    link = models.CharField(max_length=500,default='')
    image = models.ImageField(blank=True)
    suscriber = models.CharField(max_length=10,default=None)

    def __str__(self):
        return self.name

    def snippet(self):
        return self.about[0:60]

testsite/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import(
    authenticate,
    get_user_model,
    login,
    logout,
)

User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    #when we do form.is_valid it will always run clean function
    def clean(self,*args,**kwargs):
            username = self.cleaned_data.get("username")
            password = self.cleaned_data.get("password")
            user = authenticate(username=username,password=password)
            user_qs = User.objects.filter(username=username)

            if user_qs.count()==1:
                user = user_qs.first()
            if not user:
                raise forms.ValidationError("This user does not exist!!")
            if not user.check_password(password):
                raise forms.ValidationError("Password is incorrect !!")
            if not user.is_active:
                raise forms.ValidationError("This User is not longer active")
            return super(UserLoginForm,self).clean(*args,**kwargs)


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password')
    password2 = forms.CharField(label='Confirm password',widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
            'password2',
        ]
    def clean_password2(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password!=password2:
            raise forms.ValidationError("Password does't match")
        #check whether username is present in the database or not
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username is already exists")

        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("Email is already exists")
        return password

testsite/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import UserProfile,motivational,tech,music
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import(
    authenticate,
    get_user_model,
)
from .forms import UserLoginForm,UserRegisterForm


@login_required(login_url='accounts:login')
def home(request):
    user_data = UserProfile.objects.all().order_by('id')[0:3]
    moti_data = motivational.objects.all().order_by('id')[0:3]
    tech_data = tech.objects.all().order_by('id')[0:3]
    music_data = music.objects.all().order_by('id')[0:3]
    # music_data = music.objects.all().order_by('id')[0:3]
    return render(request,'accounts/home.html',{'user_data':user_data,'moti_data':moti_data,'tech_data':tech_data,'music_data':music_data})

# def register(request):
#     if request.method == 'POST':
#         form = RegistraionForm(request.POST)
#         if form.is_valid():
#             form.save()
#             login(request, user)
#             return redirect('/account')
#
#         else:
#             print(form.errors)
#     else:
#         form = RegistraionForm()
#         args = {'form':form}
#         return render(request,'accounts/reg_from.html',args)


def login(request):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username,password=password)
        auth_login(request,user)
        return redirect("/account")
    return render(request,'accounts/login.html',{"form":form})




def register(request):
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=username,password=password)
        auth_login(request,new_user)
        return redirect("/account")

    return render(request,'accounts/reg_from.html',{"form":form})


# def signup(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             return redirect('/account')
#     else:
#         form = UserCreationForm()
#     return render(request, 'accounts/reg_from.html', {'form': form})


@login_required(login_url='accounts:login')
def person_detail(request,slug):
    detail_person = UserProfile.objects.get(id=slug)
    return render(request,'accounts/detail.html',{'detail_person':detail_person})

@login_required(login_url='accounts:login')
def moti_detail(request,slug):
    moti_person = motivational.objects.get(id=slug)
    return render(request,'accounts/detail_moti.html',{'moti_person':moti_person})

@login_required(login_url='accounts:login')
def tech_detail(request,slug):
    tech_person = tech.objects.get(id=slug)
    return render(request,'accounts/detail_tech.html',{'tech_person':tech_person})

@login_required(login_url='accounts:login')
def music_detail(request,slug):
    music_person = music.objects.get(id=slug)
    return render(request,'accounts/music_detail.html',{'music_person':music_person})

def about(request):
    return render(request,'accounts/about.html')


# @login_required(login_url='accounts:login')
# def music_detail(request,slug):
#     music_person = tech.objects.get(id=slug)
#     return render(request,'accounts/music_detail.html',{'music_person':music_person})

testsite/accounts/templates/accounts/about.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <title>About</title>
  <style>
    body{
      background:   #2e3830;
      font-family:  Ubuntu;
      color: white;
    }

  </style>
{% endblock %}


{% block body %}
<div class="container">
  <br>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">TubeWiki</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/account/register">Register</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/account/login">logIn</a></li>
      </ul>
    </div>
  </div>
</nav>
  <div class="row">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
      <center><h1>About</h1></center><hr>
      <h2>In this website you will find India's top most YouTuber<br> in different different fields and contains detail each of them with<br> their YouTube channel's link </h2>
      <br>
      <br>
      <center><h4>Made with <span class="glyphicon glyphicon-heart"></span></h4></center>
    </div>
    <div class="col-sm-4">
    </div>
  </div>
</div>
{% endblock %}

testsite/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ detail_person.name }}</title>
<link rel="stylesheet" href="{% static 'accounts/detail.css' %}">
{% endblock %}


{% block body %}
<div class="container">
  <br>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">TubeWiki</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-off"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

  <center><a href="/account/"<span class="glyphicon glyphicon-home"></span></a></center><br>
    <center><img src="{{ detail_person.image.url }}" width="250" height="250"/></center>
  <div class="container">
    <center>  <h1>{{ detail_person.name }}</h1></center>
    <h1>About -:</h1>
      <h3>{{ detail_person.about }}</h3>
      <br>
      <h1>Suscriber -: {{ detail_person.suscriber }}</h1><br>
      <h1>Youtube Channel Link -:</h1>
      <h2>
      <a href="{{ detail_person.link }}">{{ detail_person.link }}</a></h2>
      <br>
      <br>
      <br>
      <div class="footer-copyright text-center py-3">© 2019 Copyright
      </div>
      <hr>

  </div>
{% endblock %}

testsite/accounts/templates/accounts/detail_moti.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ moti_person.name }}</title>
<link rel="stylesheet" href="{% static 'accounts/detail_moti.css' %}">
{% endblock %}


{% block body %}
<div class="container">
  <br>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">TubeWiki</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-off"></span></a></li>
      </ul>
    </div>
  </div>
</nav>
  <center><a href="/account/"<span class="glyphicon glyphicon-home"></span></a></center><br>
    <center><img src="{{ moti_person.image.url }}" width="250" height="250"/></center>
  <div class="container">
    <center>  <h1>{{ moti_person.name }}</h1></center>
    <h1>About -:</h1>
      <h3>{{ moti_person.about }}</h3>
      <br>
      <h1>Suscriber -: {{ moti_person.suscriber }}</h1><br>
      <h1>Youtube Channel Link -:</h1>
      <h2>
      <a href="{{ moti_person.link }}">{{ moti_person.link }}</a></h2>
      <br>
      <br>
      <br>
      <div class="footer-copyright text-center py-3">© 2019 Copyright
      </div>

      <hr>
  </div>
{% endblock %}

testsite/accounts/templates/accounts/detail_tech.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ tech_person.name }}</title>
<link rel="stylesheet" href="{% static 'accounts/detail_tech.css' %}">
{% endblock %}





{% block body %}
<div class="container">
  <br>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">TubeWiki</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-off"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

  <center><a href="/account/"<span class="glyphicon glyphicon-home"></span></a></center><br>
    <center><img src="{{ tech_person.image.url }}" width="250" height="250"/></center>
  <div class="container">
    <center>  <h1>{{ tech_person.name }}</h1></center>
    <h1>About -:</h1>
      <h3>{{ tech_person.about }}</h3>
      <br>
      <h1>Suscriber -: {{ tech_person.suscriber }}</h1><br>
      <h1>Youtube Channel Link -:</h1>
      <h2>
      <a href="{{ tech_person.link }}">{{ tech_person.link }}</a></h2>
      <br>
      <br>
      <br>
      <div class="footer-copyright text-center py-3">© 2019 Copyright
      </div>

      <hr>
  </div>
{% endblock %}

testsite/accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <title>Home</title>
  <link rel="stylesheet" href="{% static 'accounts/home.css' %}">
{% endblock %}


{% block body %}
  <div class="container">
    <br>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">TubeWiki</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">

        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-off"></span></a></li>
        </ul>
      </div>
    </div>
  </nav>






    <h1>Entertainment Club</h1><br>
    {% for i in user_data %}
      <div class="col-sm-4">
      <div class="card">
        <img class="card-img-top" src="{{ i.image.url }}" alt="Card image cap" width="150" height="150">
        <div class="card-body">
          <h2 class="card-title">{{ i.name }}</h2>
          <p class="card-text">{{ i.snippet }}......</p>
          <a href="{% url 'accounts:detail' slug=i.id %}" class="btn btn-primary">Know More</a>
          <hr>

        </div>
        </div>
      </div>
      {% endfor %}
      <center><h4><a href="/allchannel/entertainment">SEE MORE</a></h4></center>
      <h1>Motivational club</h1><br>
      {% for j in moti_data %}

        <div class="col-sm-4">
        <div class="card">
          <img class="card-img-top" src="{{ j.image.url }}" alt="Card image cap" width="150" height="150">
          <div class="card-body">
            <h2 class="card-title">{{ j.name }}</h2>
            <p class="card-text">{{ j.snippet }}......</p>
            <a href="{% url 'accounts:moti' slug=j.id %}" class="btn btn-primary">Know More</a>
            <hr>
          </div>
          </div>
        </div>

        {% endfor %}
        <center><h4><a href="/allchannel/motivational">SEE MORE</a></h4></center>

        <h1>Techonology Club</h1><br>
        {% for k in tech_data %}

          <div class="col-sm-4">
          <div class="card">
            <img class="card-img-top" src="{{ k.image.url }}" alt="Card image cap" width="150" height="150">
            <div class="card-body">
              <h2 class="card-title">{{ k.name }}</h2>
              <p class="card-text">{{ k.snippet }}......</p>
              <a href="{% url 'accounts:tech' slug=k.id %}" class="btn btn-primary">Know More</a>
              <hr>
            </div>
            </div>
          </div>

          {% endfor %}
          <center><h4><a href="/allchannel/tech">SEE MORE</a></h4></center>

          <h1>Music Club</h1><br>
          {% for l in music_data %}

            <div class="col-sm-4">
            <div class="card">
              <img class="card-img-top" src="{{ l.image.url }}" alt="Card image cap" width="150" height="150">
              <div class="card-body">
                <h2 class="card-title">{{ l.name }}</h2>
                <p class="card-text">{{ l.snippet }}......</p>
                <a href="{% url 'accounts:music' slug=l.id %}" class="btn btn-primary">Know More</a>
                <hr>
              </div>
              </div>
            </div>

            {% endfor %}
            <center><h4><a href="/allchannel/music">SEE MORE</a></h4></center>
            <br>
            <br>
            <br>
            <div class="footer-copyright text-center py-3">© 2019 Copyright
            </div>
            <br>
            <br>

{% endblock %}

testsite/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head %}
  <title>LogIn</title>
  <style>
    body{
    background:   #2e3830;
    font-family: 'Ubuntu', sans-serif;
    color:white;
  }
  </style>

{% endblock %}


{% block body %}
<div class="container">
  <br>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">TubeWiki</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="/account/about">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/account/register">Register</a></li>
      </ul>
    </div>
  </div>
</nav>
  <div class="row">
      <div class="col-sm-4">
      </div>
      <div class="col-sm-4">
        <center><h1>Welcome</h1>
        <h3><p>You can log in here!!</p></h3>
        <h2>Login</h2></center>
        <form method="post" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <center>
            <button type="submit" class="btn btn-success">LogIn</button>
            </center>
        </form>
        <br>
        <br>
        <center><h4>Made with <span class="glyphicon glyphicon-heart"></span></h4></center>

        <hr>
      </div>
      <div class="col-sm-4  ">
      </div>

  </div>
</div>
{% endblock %}

testsite/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <title>LogOut</title>
  <style>
    body{
      background:   #2e3830;
      font-family:  Ubuntu;
      color: white;
    }

  </style>
{% endblock %}


{% block body %}
<div class="container">
  <br>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">TubeWiki</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="/account/about">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/account/register">Register</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/account/login">logIn</a></li>
      </ul>
    </div>
  </div>
</nav>
  <div class="row">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
      <h1>Logged Out!!!</h1>
      <h2>You have logged Out!!</h2>

    </div>
    <div class="col-sm-4">
    </div>
  </div>
</div>
{% endblock %}

testsite/accounts/templates/accounts/music_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ music_person.name }}</title>
<link rel="stylesheet" href="{% static 'accounts/detail_tech.css' %}">
{% endblock %}





{% block body %}
<div class="container">
  <br>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">TubeWiki</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-off"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

  <center><a href="/account/"<span class="glyphicon glyphicon-home"></span></a></center><br>
    <center><img src="{{ music_person.image.url }}" width="250" height="250"/></center>
  <div class="container">
    <center>  <h1>{{ music_person.name }}</h1></center>
    <h1>About -:</h1>
      <h3>{{ music_person.about }}</h3>
      <br>
      <h1>Suscriber -: {{ music_person.suscriber }}</h1><br>
      <h1>Youtube Channel Link -:</h1>
      <h2>
      <a href="{{ music_person.link }}">{{ music_person.link }}</a></h2>
      <br>
      <br>
      <br>
      <div class="footer-copyright text-center py-3">© 2019 Copyright
      </div>

      <hr>
  </div>
{% endblock %}

testsite/accounts/templates/accounts/reg_from.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
  <title>Registraion</title>
  <style>
      body{
      background:   #2e3830;
      font-family:  Ubuntu;
      color:white;
    }
  </style>
{% endblock %}

{% block body %}
<div class="container">
  <br>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">TubeWiki</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="/account/about">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">logIn</a></li>
      </ul>
    </div>
  </div>
</nav>
  <div class="row">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
      <h1>Register Here !!</h1><hr>
      <form method="post">
        {% csrf_token %}

        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Submit</button>
        </form>
        <br>
        <br>
        <center><h4>Made with <span class="glyphicon glyphicon-heart"></span></h4></center>

        <hr>
    <div class="col-sm-4">
    </div>
    </div>
    </div>

    </div>
{% endblock %}